name: Create GitHub Issue from Workflow

on:
  push:
    branches:
      - main

permissions:
  issues: write  # Grant permission to create issues

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Issue
        run: |
          # Define the issue title and body
          issue_title="Security Issue: Sample Issue"
          issue_body="Description: This is a sample security issue detected in the repository. Please review the code for vulnerabilities."

          # Use curl to create a GitHub issue, making sure JSON is correctly escaped and quoted
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -d "{\"title\": \"${issue_title}\", \"body\": \"${issue_body}\", \"labels\": [\"security\", \"vulnerability\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues"
