name: Snyk Security Scan with SARIF Upload and Issue Creation 
on:
  push:
    branches:
      - main

permissions:
  actions: write
  issues: write  # Grant permission to create issues
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--sarif-file-output=path/snyk.sarif"

      - name: Check if SARIF file exists and print contents
        run: |
          ls -la  # List files to check if snyk.sarif exists
          cat path/snyk.sarif  # Display the contents of the SARIF file

      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: path/snyk.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

     
