name: Create GitHub Issue from Workflow

on:
  push:
    branches:
      - main  # or specify the branch you want to track
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run security checks (example)
      id: security_check
      run: |
        # Example: Simulate a security check
        if [[ $(grep -c "hardcoded" app.py) -gt 0 ]]; then
          echo "Hardcoded credentials found!"
          echo "security_check_failed=true" >> $GITHUB_ENV
        else
          echo "No issues found"
        fi

  create_issue:
    runs-on: ubuntu-latest
    needs: check_security
    if: env.security_check_failed == 'true'
    steps:
    - name: Create GitHub Issue
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: "Security Issue: Hardcoded Credentials Found"
        body: |
          The security check found hardcoded credentials in the code.
          
          Please remove any hardcoded credentials to prevent security risks.
        labels: security, bug
        token: ${{ secrets.GITHUB_TOKEN }}
