name: Snyk Security Scan with SARIF Upload and Issue Creation

on:
  push:
    branches:
      - main

permissions:
  actions: write
  issues: write  # Grant permission to create issues
  security-events: write
  contents: read  # Required to fetch code scanning alerts

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--sarif-file-output=path/snyk.sarif"

      - name: Check if SARIF file exists and print contents
        run: |
          ls -la  # List files to check if snyk.sarif exists
          cat path/snyk.sarif  # Display the contents of the SARIF file

      - name: Upload SARIF report to GitHub
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: path/snyk.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

      - name: Fetch Code Scanning Alerts and Create Issues
        if: success() && steps.upload-sarif.outputs.upload-success == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch code scanning alerts
          ALERTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open")

          # Loop through alerts and create issues
          echo "$ALERTS" | jq -c '.[]' | while read -r alert; do
            alert_id=$(echo "$alert" | jq -r '.number')
            alert_title=$(echo "$alert" | jq -r '.rule.description')
            alert_url=$(echo "$alert" | jq -r '.html_url')

            # Create issue for each alert
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{
                \"title\": \"Fix code scanning alert - $alert_title\",
                \"body\": \"<!-- Warning: The suggested title contains the alert rule name. This can expose security information. -->\n\nTracking issue for:\n- [ ] $alert_url\"
              }" \
              "https://api.github.com/repos/${{ github.repository }}/issues"
          done
