name: Code Scanning and Create GitHub Issues

on:
  push:
    branches:
      - main

permissions:
  issues: write  # Grant permission to create issues
  security-events: write  # Grant permission to upload code scanning results

jobs:
  scan-and-create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk
        run: |
          npm install -g snyk

      - name: Run Snyk for Node.js
        run: |
          snyk test --file=package.json --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check if SARIF file exists and print contents
        run: |
          if [ -f "snyk.sarif" ]; then
            echo "SARIF file found!"
            cat snyk.sarif
          else
            echo "SARIF file not found. Please check your configuration."
            exit 1
          fi

      - name: Upload SARIF report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Issues from SARIF
        run: |
          # Parse SARIF and extract issues
          issues=$(cat snyk.sarif | jq -r '.runs[0].results[] | "\(.message.text) - File: \(.locations[0].physicalLocation.artifactLocation.uri) Line: \(.locations[0].physicalLocation.region.startLine)"')

          # If no issues found, exit early
          if [ -z "$issues" ]; then
            echo "No issues found in SARIF report"
            exit 0
          fi

          # Iterate through the issues and create GitHub issues
          for issue in $issues; do
            title=$(echo "$issue" | cut -d'-' -f1)
            file_and_line=$(echo "$issue" | cut -d'-' -f2)

            echo "Creating issue: $title"

            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"title\": \"Security Issue: $title\", \"body\": \"Description: This issue was detected by SARIF scan. Please review. Location: $file_and_line.\", \"labels\": [\"security\", \"vulnerability\"]}" \
              "https://api.github.com/repos/${{ github.repository }}/issues" \
              -w "\nResponse code: %{http_code}\n"
          done
